/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoryMachineRouteImport } from './routes/category.machine'
import { Route as CategoryLivestockRouteImport } from './routes/category.livestock'
import { Route as CategoryFisheriesRouteImport } from './routes/category.fisheries'
import { Route as CategoryCropsRouteImport } from './routes/category.crops'
import { Route as AuthUnauthorizedRouteImport } from './routes/auth.unauthorized'
import { Route as AuthSuccessRouteImport } from './routes/auth.success'
import { Route as AuthErrorRouteImport } from './routes/auth.error'
import { Route as AuthConfirmRouteImport } from './routes/auth.confirm'
import { Route as AdminVideosRouteImport } from './routes/admin.videos'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminChatRoomRouteImport } from './routes/admin.chat-room'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryMachineRoute = CategoryMachineRouteImport.update({
  id: '/category/machine',
  path: '/category/machine',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryLivestockRoute = CategoryLivestockRouteImport.update({
  id: '/category/livestock',
  path: '/category/livestock',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryFisheriesRoute = CategoryFisheriesRouteImport.update({
  id: '/category/fisheries',
  path: '/category/fisheries',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCropsRoute = CategoryCropsRouteImport.update({
  id: '/category/crops',
  path: '/category/crops',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUnauthorizedRoute = AuthUnauthorizedRouteImport.update({
  id: '/auth/unauthorized',
  path: '/auth/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSuccessRoute = AuthSuccessRouteImport.update({
  id: '/auth/success',
  path: '/auth/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVideosRoute = AdminVideosRouteImport.update({
  id: '/admin/videos',
  path: '/admin/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChatRoomRoute = AdminChatRoomRouteImport.update({
  id: '/admin/chat-room',
  path: '/admin/chat-room',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/admin/applications',
  path: '/admin/applications',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/chat-room': typeof AdminChatRoomRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/success': typeof AuthSuccessRoute
  '/auth/unauthorized': typeof AuthUnauthorizedRoute
  '/category/crops': typeof CategoryCropsRoute
  '/category/fisheries': typeof CategoryFisheriesRoute
  '/category/livestock': typeof CategoryLivestockRoute
  '/category/machine': typeof CategoryMachineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/chat-room': typeof AdminChatRoomRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/success': typeof AuthSuccessRoute
  '/auth/unauthorized': typeof AuthUnauthorizedRoute
  '/category/crops': typeof CategoryCropsRoute
  '/category/fisheries': typeof CategoryFisheriesRoute
  '/category/livestock': typeof CategoryLivestockRoute
  '/category/machine': typeof CategoryMachineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/chat-room': typeof AdminChatRoomRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/success': typeof AuthSuccessRoute
  '/auth/unauthorized': typeof AuthUnauthorizedRoute
  '/category/crops': typeof CategoryCropsRoute
  '/category/fisheries': typeof CategoryFisheriesRoute
  '/category/livestock': typeof CategoryLivestockRoute
  '/category/machine': typeof CategoryMachineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/admin/applications'
    | '/admin/chat-room'
    | '/admin/users'
    | '/admin/videos'
    | '/auth/confirm'
    | '/auth/error'
    | '/auth/success'
    | '/auth/unauthorized'
    | '/category/crops'
    | '/category/fisheries'
    | '/category/livestock'
    | '/category/machine'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/admin/applications'
    | '/admin/chat-room'
    | '/admin/users'
    | '/admin/videos'
    | '/auth/confirm'
    | '/auth/error'
    | '/auth/success'
    | '/auth/unauthorized'
    | '/category/crops'
    | '/category/fisheries'
    | '/category/livestock'
    | '/category/machine'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/admin/applications'
    | '/admin/chat-room'
    | '/admin/users'
    | '/admin/videos'
    | '/auth/confirm'
    | '/auth/error'
    | '/auth/success'
    | '/auth/unauthorized'
    | '/category/crops'
    | '/category/fisheries'
    | '/category/livestock'
    | '/category/machine'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminChatRoomRoute: typeof AdminChatRoomRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVideosRoute: typeof AdminVideosRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  AuthErrorRoute: typeof AuthErrorRoute
  AuthSuccessRoute: typeof AuthSuccessRoute
  AuthUnauthorizedRoute: typeof AuthUnauthorizedRoute
  CategoryCropsRoute: typeof CategoryCropsRoute
  CategoryFisheriesRoute: typeof CategoryFisheriesRoute
  CategoryLivestockRoute: typeof CategoryLivestockRoute
  CategoryMachineRoute: typeof CategoryMachineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/machine': {
      id: '/category/machine'
      path: '/category/machine'
      fullPath: '/category/machine'
      preLoaderRoute: typeof CategoryMachineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/livestock': {
      id: '/category/livestock'
      path: '/category/livestock'
      fullPath: '/category/livestock'
      preLoaderRoute: typeof CategoryLivestockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/fisheries': {
      id: '/category/fisheries'
      path: '/category/fisheries'
      fullPath: '/category/fisheries'
      preLoaderRoute: typeof CategoryFisheriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/crops': {
      id: '/category/crops'
      path: '/category/crops'
      fullPath: '/category/crops'
      preLoaderRoute: typeof CategoryCropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/unauthorized': {
      id: '/auth/unauthorized'
      path: '/auth/unauthorized'
      fullPath: '/auth/unauthorized'
      preLoaderRoute: typeof AuthUnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/success': {
      id: '/auth/success'
      path: '/auth/success'
      fullPath: '/auth/success'
      preLoaderRoute: typeof AuthSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/videos': {
      id: '/admin/videos'
      path: '/admin/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AdminVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/chat-room': {
      id: '/admin/chat-room'
      path: '/admin/chat-room'
      fullPath: '/admin/chat-room'
      preLoaderRoute: typeof AdminChatRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/admin/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminChatRoomRoute: AdminChatRoomRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVideosRoute: AdminVideosRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  AuthErrorRoute: AuthErrorRoute,
  AuthSuccessRoute: AuthSuccessRoute,
  AuthUnauthorizedRoute: AuthUnauthorizedRoute,
  CategoryCropsRoute: CategoryCropsRoute,
  CategoryFisheriesRoute: CategoryFisheriesRoute,
  CategoryLivestockRoute: CategoryLivestockRoute,
  CategoryMachineRoute: CategoryMachineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
